### ISSUE TITLE
Insufficient account balance for this operation?

### ISSUE THREAD

**Issue by AxlMaid** [maidsafe/safe_examples#213]
I got this message when I try uploading more files to the Web Hosting Manager: "Insufficient account balance for this operation".
What does this mean? What am I supposed to do?

Thanks,

Axl
![screen shot 2017-07-17 at 00 28 56](https://user-images.githubusercontent.com/30219645/28251902-21789dc0-6a87-11e7-9b49-46c528c99a8c.png)

**Comment by krishnaIndia** [comment]
Will take it as an improvement task. The error displayed is because the user account limit is reached. Every account has a maximum permitted storage. This error remarks that the account has used its maximum. I agree that the error is not readable. Will present it better. Have raised a [task](https://maidsafe.atlassian.net/browse/MAID-2138) for the same in JIRA. Cheers!

**Comment by frabrunelle** [comment]
This issue has been fixed by #215.

The displayed error should be a bit clearer now:

> Network operation is not possible as there is insufficient account balance

As mentioned in the [Test 17 topic](https://safenetforum.org/t/maidsafe-dev-update-july-13-2017-test-17/14769), each client account is limited to 500 operations. Currently the amount of operations used is not displayed in the browser UI. We're working on addressing this to be shown in the browser itself to allow users to keep track of this amount. It's worth noting that this number is just a temporary placeholder and is shared between all the apps on a given account.
