### ISSUE TITLE
Files/directory remain in demo app after failing upload

### ISSUE THREAD

**Issue by aenemic** [maidsafe/safe_examples#79]
When an upload fails, the directory or file is still stored on the network but with 0kb, which means one will have to delete it before reuploading. Wouldnt it make more sense to run a delete function if upload fails?

**Comment by krishnaIndia** [comment]
This is a known limitation for now, @aenemic. I don't think just because the upload failed the app should decide to delete the file, instead this should be left to the user IMO. There are situations where the demo app says the upload failed for some reason and the file seems to be updated after few minutes. There is certainly some lag here. Which will be resolved in the next patch update.
